### ISSUE TITLE
Add support for GHC Head

### ISSUE THREAD

**Issue by ndmitchell** [haskell/primitive#229]
The current released version doesn't support GHC HEAD.

```
[ 7 of 15] Compiling Data.Primitive.MutVar ( Data/Primitive/MutVar.hs, dist/build/Data/Primitive/MutVar.o )
Data/Primitive/MutVar.hs:29:46: error:
    Module ‘GHC.Prim’ does not export ‘atomicModifyMutVar#’
   |
29 |                   readMutVar#, writeMutVar#, atomicModifyMutVar# )
   |                                              ^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-7047/primitive-0.6.4.0'
```

It looks like this code has changed in the git repo. Any chance of making a new release, so that anything downstream of `primitive` can test with GHC HEAD nice and far in advance, and thus report issues to GHC before it's too late?

**Comment by chessai** [comment]
I think this is related to #200. I agree there should be a bugfix release that also builds with HEAD, before the release of  8.8.1-alpha

**Comment by cartazio** [comment]
there is a release that builds on 8.8 http://hackage.haskell.org/package/primitive-0.6.1.2

**Comment by cartazio** [comment]
most extent primitive code doens't depend on more recent primitive features afaik, but yes, some releases on the most recent minor version family are pending

**Comment by cartazio** [comment]
(i have some patch sets in my release queue for that bug fix release
)

**Comment by cartazio** [comment]
closing for now. 0.7 will be out soon too
