### PR TITLE
Use GHC.Exts to import unsafeCoerce# et al.

### LINKED ISSUE #258: Import unsafeCoerce# from GHC.Exts, not GHC.Base
`primitive` (both version 0.7.0.0 and on the `master` branch) fail to compile on GHC HEAD (8.11) after [this commit](https://gitlab.haskell.org/ghc/ghc/commit/74ad75e87317196c600dfabc61aee1b87d95c214):

```
[ 1 of 13] Compiling Control.Monad.Primitive ( Control/Monad/Primitive.hs, dist/build/Control/Monad/Primitive.o, dist/build/Control/Monad/Primitive.dyn_o )

Control/Monad/Primitive.hs:27:21: error:
    Module ‘GHC.Base’ does not export ‘unsafeCoerce#’
   |
27 | import GHC.Base   ( unsafeCoerce#, realWorld# )
   |                     ^^^^^^^^^^^^^
```

The reason is that `unsafeCoerce#` was moved from `GHC.Prim` (which `GHC.Base` reexports) to `Unsafe.Coerce`. Luckily, there is a backwards-compatible way to fix this: just import `unsafeCoerce#` from `GHC.Exts` instead, which has better stability API-wise.

More generally, I wonder if we should switch all `GHC.Base` imports to `GHC.Exts` (_à la_ #197) since `GHC.Base` has proven to be volatile like `GHC.Prim`.

### PR DESCRIPTION
**Pull request by RyanGlScott**
`unsafeCoerce#` can no longer be imported from `GHC.Base` on GHC HEAD, so this patch changes the import to `GHC.Exts` instead. While I was in town, I removed some unnecessary CPP (`primitive` supports GHC 7.4 as the minimum, so `MIN_VERSION_base(4,2,0)` and `MIN_VERSION_base(4,4,0)` are always true) and consolidated some other `GHC.Base` imports to use `GHC.Exts` instead.

Fixes #258.

### CODE REVIEW

**Comment by simonpj** [comment]
Good plan!

**Comment by cartazio** [comment]
Cool. I’ll cut a release post haste.  
No need to revise bounds on current releases I assume?

**Comment by RyanGlScott** [comment]
> No need to revise bounds on current releases I assume?

Correct—the upper version bounds on `base` on existing releases are already sufficient. This change should only affect those who are adventurous to build `primitive` with the necessary `--allow-newer` flags (e.g., GHC HEAD users like myself).

**Comment by osa1** [comment]
Can we merge this please? This will reduce the number of steps I have to take to build stuff with GHC HEAD. Ping @cartazio .

**Comment by cartazio** [comment]
@osa1  you already asked me twice on irc, github doesn't have better latency over irc :P

**Comment by osa1** [comment]
@cartazio I asked you here first, and only asked on IRC once not twice.

**Comment by cartazio** [comment]
:) on it :)

**Comment by cartazio** [comment]
ok, i have a candidate here for 0.7.0.1 based off commit 9c8cf3bc12754ec095629ddb1e06c754c7b08855
(reverted the two minor version bump changes relative to the last release)
https://hackage.haskell.org/package/primitive-0.7.0.1/candidate 

generated/uploaded tarball should be 
`
 $ shasum -a256 dist-newstyle/sdist/primitive-0.7.0.1.tar.gz
dd8bb7d829f492d6200fca4a839a7563b80571c5f76b4d0fa76700ebe897f7dd  dist-newstyle/sdist/primitive-0.7.0.1.tar.gz
`

@chessai @osa1  @RyanGlScott  @andrewthad 

please confirm this looks reasonable and i'll do the final upload (and then do some backlogged cleanup for master on outstanding/fantastic prs that aren't merged in yet)

**Comment by chessai** [comment]
LGTM
