### ISSUE TITLE
Import unsafeCoerce# from GHC.Exts, not GHC.Base

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/primitive#258]
`primitive` (both version 0.7.0.0 and on the `master` branch) fail to compile on GHC HEAD (8.11) after [this commit](https://gitlab.haskell.org/ghc/ghc/commit/74ad75e87317196c600dfabc61aee1b87d95c214):

```
[ 1 of 13] Compiling Control.Monad.Primitive ( Control/Monad/Primitive.hs, dist/build/Control/Monad/Primitive.o, dist/build/Control/Monad/Primitive.dyn_o )

Control/Monad/Primitive.hs:27:21: error:
    Module ‘GHC.Base’ does not export ‘unsafeCoerce#’
   |
27 | import GHC.Base   ( unsafeCoerce#, realWorld# )
   |                     ^^^^^^^^^^^^^
```

The reason is that `unsafeCoerce#` was moved from `GHC.Prim` (which `GHC.Base` reexports) to `Unsafe.Coerce`. Luckily, there is a backwards-compatible way to fix this: just import `unsafeCoerce#` from `GHC.Exts` instead, which has better stability API-wise.

More generally, I wonder if we should switch all `GHC.Base` imports to `GHC.Exts` (_à la_ #197) since `GHC.Base` has proven to be volatile like `GHC.Prim`.

**Comment by RyanGlScott** [comment]
It looks like we can't switch _all_ `GHC.Base` imports to `GHC.Exts`, since there are some old GHC releases where their differences actually impact `primitive`. See, for instance, this piece of CPP in `Data.Primitive.SmallArray`:

https://github.com/haskell/primitive/blob/3486c93c3b96e17533a8d4cbac8b1e4ea7e812f2/Data/Primitive/SmallArray.hs#L93-L97

Still, switching the `GHC.Base` import to `GHC.Exts` in `Control.Monad.Primitive` (which is what is actually broken on GHC HEAD) should be straightforward. I'll prepare a PR that accomplishes that.

**Comment by osa1** [comment]
I wonder if we should make some effort to keep the breakage minimal by exporting `unsafeCoerce#` in some of the modules where it was exported before, like `GHC.Base` (not sure where else it was exported from). 

`unsafeCoerce#` was previously a magic `Id` defined in `GHC.Prim`. It's still pretty magical, but it now has a placeholder definition in `Unsafe.Coerce` so that's where it lives now.

I don't understand how `GHC.Prim` is implemented so I'm not sure if exporting it from there is a possibility, but perhaps we could export it from `GHC.Prim.Ext`? `GHC.Prim.Ext` has a very specific use case ("Extra C-- routines exposed from the RTS") but maybe we can generalize it a little bit.

**Comment by RyanGlScott** [comment]
My view is that the only module GHC needs to spend any sort of effort avoiding breakages in is `GHC.Exts`, since that modules Haddocks [explicitly advertise](https://hackage.haskell.org/package/base-4.12.0.0/docs/GHC-Exts.html) it as "the Approved Way to get at GHC-specific extensions". `GHC.Prim` is essentially an autogenerated list of primops, so changing anything from a primop to a non-primop will necessarily force it to live outside of `GHC.Prim`. I don't view this as a bad thing—this gives GHC developers the flexibility to redesign core internals as they see fit while still maintaining some semblance of backwards compatibility by reexporting things through `GHC.Exts`.
